# Weather API Extractor - Project Configuration
# MVP Proof-of-Concept for Example-Driven Extraction Platform
#
# This project demonstrates the platform's capability to generate data extractors
# from input/output examples. It extracts current weather data from OpenWeatherMap API
# and demonstrates all key transformation patterns.

project:
  name: weather_api_extractor
  description: Extract current weather data from OpenWeatherMap API using example-driven transformation
  version: 1.0.0
  author: Platform MVP Team
  tags:
    - weather
    - api
    - mvp
    - proof-of-concept

# Data source configuration
data_sources:
  - type: api
    name: openweathermap
    endpoint: https://api.openweathermap.org/data/2.5/weather

    # Authentication using environment variable (secure)
    auth:
      type: api_key
      key: ${OPENWEATHER_API_KEY}
      param_name: appid

    # Default parameters for all requests
    parameters:
      units: metric  # Use Celsius for temperature

    # Custom headers
    headers:
      User-Agent: WeatherExtractorMVP/1.0

    # Caching configuration (reduce API calls)
    cache:
      enabled: true
      ttl: 1800  # 30 minutes cache
      cache_dir: data/cache/weather

    # Rate limiting (respect API limits)
    rate_limit:
      requests_per_second: 0.5  # Max 30 calls per minute on free tier
      burst_size: 3

    # Reliability settings
    timeout: 10
    max_retries: 3

# Example input/output pairs - Diverse weather conditions
# These examples teach the AI how to transform raw API responses
examples:
  # Example 1: Rainy, temperate climate (London)
  - input:
      coord:
        lon: -0.1257
        lat: 51.5085
      weather:
        - id: 500
          main: Rain
          description: light rain
          icon: 10d
      base: stations
      main:
        temp: 15.5
        feels_like: 14.2
        temp_min: 14.0
        temp_max: 17.0
        pressure: 1012
        humidity: 72
      visibility: 10000
      wind:
        speed: 4.1
        deg: 230
      clouds:
        all: 75
      dt: 1701360000
      sys:
        type: 2
        id: 2019646
        country: GB
        sunrise: 1701331200
        sunset: 1701362400
      timezone: 0
      id: 2643743
      name: London
      cod: 200
    output:
      city: London
      country: GB
      temperature_c: 15.5
      feels_like_c: 14.2
      humidity_percent: 72
      pressure_hpa: 1012
      wind_speed_ms: 4.1
      conditions: light rain
      cloudiness_percent: 75
      visibility_m: 10000
    description: "Rainy temperate climate - demonstrates nested field extraction and array handling"

  # Example 2: Clear sky, moderate (Tokyo)
  - input:
      coord:
        lon: 139.6917
        lat: 35.6895
      weather:
        - id: 800
          main: Clear
          description: clear sky
          icon: 01d
      base: stations
      main:
        temp: 18.2
        feels_like: 17.5
        temp_min: 16.0
        temp_max: 20.0
        pressure: 1015
        humidity: 55
      visibility: 10000
      wind:
        speed: 2.5
        deg: 180
      clouds:
        all: 0
      dt: 1701360000
      sys:
        type: 1
        id: 8074
        country: JP
        sunrise: 1701295200
        sunset: 1701331200
      timezone: 32400
      id: 1850144
      name: Tokyo
      cod: 200
    output:
      city: Tokyo
      country: JP
      temperature_c: 18.2
      feels_like_c: 17.5
      humidity_percent: 55
      pressure_hpa: 1015
      wind_speed_ms: 2.5
      conditions: clear sky
      cloudiness_percent: 0
      visibility_m: 10000
    description: "Clear moderate weather - baseline case"

  # Example 3: Snowy, cold climate (Moscow)
  - input:
      coord:
        lon: 37.6156
        lat: 55.7522
      weather:
        - id: 601
          main: Snow
          description: snow
          icon: 13d
      base: stations
      main:
        temp: -8.0
        feels_like: -12.5
        temp_min: -10.0
        temp_max: -6.0
        pressure: 1020
        humidity: 85
      visibility: 5000
      wind:
        speed: 5.5
        deg: 320
      clouds:
        all: 90
      dt: 1701360000
      sys:
        type: 1
        id: 9029
        country: RU
        sunrise: 1701323400
        sunset: 1701349800
      timezone: 10800
      id: 524901
      name: Moscow
      cod: 200
    output:
      city: Moscow
      country: RU
      temperature_c: -8.0
      feels_like_c: -12.5
      humidity_percent: 85
      pressure_hpa: 1020
      wind_speed_ms: 5.5
      conditions: snow
      cloudiness_percent: 90
      visibility_m: 5000
    description: "Snowy cold climate - demonstrates negative temperatures and reduced visibility"

  # Example 4: Hot, dry climate (Dubai)
  - input:
      coord:
        lon: 55.3047
        lat: 25.2582
      weather:
        - id: 800
          main: Clear
          description: clear sky
          icon: 01d
      base: stations
      main:
        temp: 35.0
        feels_like: 38.5
        temp_min: 33.0
        temp_max: 37.0
        pressure: 1010
        humidity: 25
      visibility: 10000
      wind:
        speed: 3.5
        deg: 90
      clouds:
        all: 0
      dt: 1701360000
      sys:
        type: 1
        id: 7537
        country: AE
        sunrise: 1701314400
        sunset: 1701350400
      timezone: 14400
      id: 292223
      name: Dubai
      cod: 200
    output:
      city: Dubai
      country: AE
      temperature_c: 35.0
      feels_like_c: 38.5
      humidity_percent: 25
      pressure_hpa: 1010
      wind_speed_ms: 3.5
      conditions: clear sky
      cloudiness_percent: 0
      visibility_m: 10000
    description: "Hot dry climate - demonstrates high temperatures and low humidity"

  # Example 5: Cold, windy climate (Oslo)
  - input:
      coord:
        lon: 10.7461
        lat: 59.9127
      weather:
        - id: 803
          main: Clouds
          description: broken clouds
          icon: 04d
      base: stations
      main:
        temp: 2.0
        feels_like: -3.0
        temp_min: 0.0
        temp_max: 4.0
        pressure: 1005
        humidity: 78
      visibility: 8000
      wind:
        speed: 7.5
        deg: 280
      clouds:
        all: 60
      dt: 1701360000
      sys:
        type: 1
        id: 1418
        country: "NO"
        sunrise: 1701334800
        sunset: 1701357600
      timezone: 3600
      id: 3143244
      name: Oslo
      cod: 200
    output:
      city: Oslo
      country: "NO"
      temperature_c: 2.0
      feels_like_c: -3.0
      humidity_percent: 78
      pressure_hpa: 1005
      wind_speed_ms: 7.5
      conditions: broken clouds
      cloudiness_percent: 60
      visibility_m: 8000
    description: "Cold windy climate - demonstrates wind chill effect (feels_like < actual)"

  # Example 6: Humid tropical (Singapore)
  - input:
      coord:
        lon: 103.8501
        lat: 1.2897
      weather:
        - id: 501
          main: Rain
          description: moderate rain
          icon: 10d
      base: stations
      main:
        temp: 28.0
        feels_like: 32.5
        temp_min: 27.0
        temp_max: 29.0
        pressure: 1008
        humidity: 88
      visibility: 7000
      wind:
        speed: 1.5
        deg: 150
      clouds:
        all: 85
      dt: 1701360000
      sys:
        type: 1
        id: 9470
        country: SG
        sunrise: 1701300000
        sunset: 1701343200
      timezone: 28800
      id: 1880252
      name: Singapore
      cod: 200
    output:
      city: Singapore
      country: SG
      temperature_c: 28.0
      feels_like_c: 32.5
      humidity_percent: 88
      pressure_hpa: 1008
      wind_speed_ms: 1.5
      conditions: moderate rain
      cloudiness_percent: 85
      visibility_m: 7000
    description: "Humid tropical - demonstrates high humidity and heat index effect"

  # Example 7: Variable weather (New York)
  - input:
      coord:
        lon: -74.0060
        lat: 40.7128
      weather:
        - id: 701
          main: Mist
          description: mist
          icon: 50d
      base: stations
      main:
        temp: 12.0
        feels_like: 10.5
        temp_min: 10.0
        temp_max: 14.0
        pressure: 1013
        humidity: 68
      visibility: 6000
      wind:
        speed: 3.0
        deg: 200
      clouds:
        all: 50
      dt: 1701360000
      sys:
        type: 1
        id: 4610
        country: US
        sunrise: 1701337200
        sunset: 1701371400
      timezone: -18000
      id: 5128581
      name: New York
      cod: 200
    output:
      city: New York
      country: US
      temperature_c: 12.0
      feels_like_c: 10.5
      humidity_percent: 68
      pressure_hpa: 1013
      wind_speed_ms: 3.0
      conditions: mist
      cloudiness_percent: 50
      visibility_m: 6000
    description: "Misty conditions - demonstrates reduced visibility edge case"

# Validation rules - ensure data quality
validation:
  # Required fields in every output
  required_fields:
    - city
    - country
    - temperature_c
    - humidity_percent
    - conditions

  # Field type definitions
  field_types:
    city: str
    country: str
    temperature_c: float
    feels_like_c: float
    humidity_percent: int
    pressure_hpa: int
    wind_speed_ms: float
    conditions: str
    cloudiness_percent: int
    visibility_m: int

  # Value constraints for data validation
  constraints:
    temperature_c:
      min: -60.0  # Extreme cold (Oymyakon, Russia)
      max: 60.0   # Extreme heat (Death Valley)
    humidity_percent:
      min: 0
      max: 100
    pressure_hpa:
      min: 870    # Lowest recorded (Typhoon Tip)
      max: 1085   # Highest recorded (Siberian High)
    wind_speed_ms:
      min: 0.0
      max: 113.0  # Category 5 hurricane (~250 mph)
    cloudiness_percent:
      min: 0
      max: 100
    visibility_m:
      min: 0
      max: 100000  # Maximum useful visibility

  # Allow extra fields that might be in examples but not defined
  allow_extra_fields: true

# Output configuration
output:
  formats:
    # CSV output for data analysis
    - type: csv
      path: output/weather_data.csv
      include_timestamp: false
      options:
        delimiter: ","
        quoting: minimal

    # JSON output for API integration
    - type: json
      path: output/weather_data.json
      pretty_print: true
      include_timestamp: false

# Runtime execution settings
runtime:
  log_level: INFO
  parallel: false  # Sequential for MVP (can enable for production)
  max_workers: 1
  error_strategy: continue  # Continue on errors, log them

  # Checkpointing for long-running extractions
  checkpoint_enabled: false
  checkpoint_interval: 10
  checkpoint_dir: data/checkpoints/weather
